version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

files:
  - source: /src/simple-reactjs-app
    destination: /home/ec2-user/web

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 20
      runas: ec2-user
  BeforeInstall:
    - location: installdependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: validate.sh
      timeout: 120
      runas: ec2-user