version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server
  - source: /simple-reactjs-app/
    destination: /home/ec2-user/simple-reactjs-app
  - source: /simple-reactjs-app/*
    destination: /home/ec2-user/simple-reactjs-app/


permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
      runas: ec2-user
  BeforeInstall:
    - location: scripts/installdependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      timeout: 120
      runas: ec2-user