version: 0.2

env:
  variables:
    vargitCommitID: "initial null"
    variable: "initla variable null"

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
  #    - echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8

      - export var1=$(echo "hello world" | cut -c -2)
      - echo $var1
      
      # - export var2=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      # - echo $var2 

      - export var2=$(echo ($CODEBUILD_RESOLVED_SOURCE_VERSION)| cut -c1-8)
      - echo $var2 
      - mvn clean install 
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - mvn package
      
cache:
  paths:
    - '/root/.m2/**/*'

artifacts:
  files:
#    - target/springbootdemo-0.0.1-SNAPSHOT.jar
    - target/springbootdemo-0.0.1-SNAPSHOT$var2.jar
    - appspec.yml
    - scripts/*
    - simple-reactjs-app/*
    - simple-reactjs-app/**/*

    