version: 0.2

env:
  variables:
    commitID: "initial null"

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - export commitID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c -8)
      - echo $commitID 
      - mvn clean install 
      
cache:
  paths:
    - '/root/.m2/**/*'

artifacts:
  files:
    - target/springbootdemo-0.0.1-SNAPSHOT$commitID.jar
    - appspec.yml
    - scripts/*
    - simple-reactjs-app/*
    - simple-reactjs-app/**/*

    