version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8
      - echo $SourceVariables.CommitId
      - mvn clean install 
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - mvn package
      
cache:
  paths:
    - '/root/.m2/**/*'

artifacts:
  files:
    - target/springbootdemo-0.0.1-SNAPSHOT.jar
#    - [target/springbootdemo-0.0.1-SNAPSHOT, $SourceVariables.CommitId, .jar]
    - appspec.yml
    - scripts/*
    - simple-reactjs-app/*
    - simple-reactjs-app/**/*

    